import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { X } from 'lucide-react'
import { useCarrinhoContext } from '../context/CarrinhoContext'
import { formatarPreco } from '../lib/formatar'

export default function CarrinhoDrawer() {
  const { itens, adicionar, diminuir, remover, total, carrinhoAberto, fecharCarrinho } = useCarrinhoContext()
  useEffect(() => { if (!carrinhoAberto) return; const close = (event: KeyboardEvent) => event.key === 'Escape' && fecharCarrinho(); document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close) } }, [carrinhoAberto, fecharCarrinho])
  return <><div aria-hidden={!carrinhoAberto} onClick={fecharCarrinho} className={`fixed inset-0 z-[60] bg-black/60 transition-opacity duration-300 ${carrinhoAberto ? 'opacity-100' : 'pointer-events-none opacity-0'}`} /><aside aria-label="Carrinho de compras" aria-hidden={!carrinhoAberto} className={`fixed right-0 top-0 z-[70] flex h-full w-full max-w-md flex-col border-l border-ouro/20 bg-bordo shadow-2xl transition-transform duration-300 ease-out ${carrinhoAberto ? 'translate-x-0' : 'translate-x-full'}`}><header className="flex items-center justify-between border-b border-ouro/20 px-6 py-5"><div><p className="font-label text-[10px] uppercase tracking-[0.25em] text-ouro">Sua seleção</p><h2 className="mt-1 font-titulo text-3xl text-creme">Seu carrinho</h2></div><button type="button" onClick={fecharCarrinho} className="text-bege transition hover:text-ouro" aria-label="Fechar carrinho"><X size={24} /></button></header><div className="flex-1 overflow-y-auto px-6 py-5">{!itens.length ? <div className="flex h-full flex-col items-center justify-center text-center"><p className="font-titulo text-2xl text-creme">Seu carrinho está vazio</p><Link to="/loja" onClick={fecharCarrinho} className="mt-4 text-ouro underline underline-offset-4">Conheça a loja</Link></div> : <div className="space-y-4">{itens.map(item => <div key={item.id} className="border-b border-ouro/15 pb-4"><div className="flex items-start justify-between gap-4"><div><h3 className="font-titulo text-xl text-creme">{item.nome}</h3><p className="text-sm text-bege">{formatarPreco(item.preco)}</p></div><button type="button" onClick={() => remover(item.id)} className="text-xs text-sangue hover:text-rubi">Remover</button></div><div className="mt-3 flex items-center gap-4 text-creme"><button type="button" onClick={() => diminuir(item.id)} className="h-7 w-7 rounded-full border border-ouro/30 text-ouro">−</button><span>{item.quantidade}</span><button type="button" onClick={() => adicionar(item)} className="h-7 w-7 rounded-full border border-ouro/30 text-ouro">+</button></div></div>)}</div>}</div>{itens.length > 0 && <footer className="border-t border-ouro/20 px-6 py-5"><div className="mb-4 flex justify-between text-lg text-creme"><span>Total</span><strong>{formatarPreco(total)}</strong></div><Link to="/checkout" onClick={fecharCarrinho} className="block w-full rounded-xl bg-ouro px-5 py-3 text-center font-label text-xs uppercase tracking-widest text-preto transition hover:bg-champanhe">Ir para pagamento</Link></footer>}</aside></>
}
