import * as React from 'react'
import { Link, useNavigate } from 'react-router-dom'

export function SignIn1() {
  const [email, setEmail] = React.useState(''); const [password, setPassword] = React.useState(''); const [register, setRegister] = React.useState(false); const [error, setError] = React.useState(''); const [loading, setLoading] = React.useState(false); const navigate = useNavigate()
  async function handleSignIn(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); try { const response = await fetch(`/api/auth/${register ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Não foi possível entrar.'); return }; navigate('/checkout') } catch { setError('Não foi possível conectar ao servidor.') } finally { setLoading(false) } }
  return <main className="relative flex min-h-[calc(100svh-9rem)] w-full items-center justify-center overflow-hidden bg-preto px-6 py-16"><div className="pointer-events-none absolute -left-32 top-0 h-80 w-80 rounded-full bg-vinho/50 blur-3xl" /><div className="pointer-events-none absolute -right-32 bottom-0 h-96 w-96 rounded-full bg-sangue/20 blur-3xl" /><div className="relative z-10 w-full max-w-md rounded-[2rem] border border-ouro/25 bg-gradient-to-br from-vinho/90 to-preto/95 p-8 shadow-2xl shadow-black/40 backdrop-blur-sm sm:p-10"><div className="mb-7 flex h-14 w-14 items-center justify-center rounded-full border border-ouro/40 bg-ouro/10 text-3xl text-ouro shadow-lg">✦</div><p className="font-script text-3xl text-champanhe">Linhas da Menina</p><h1 className="mt-2 font-titulo text-4xl font-semibold text-creme">{register ? 'Criar sua conta' : 'Bem-vinda de volta'}</h1><p className="mt-2 text-base text-bege">{register ? 'Entre para acompanhar seus pedidos.' : 'Acesse sua conta para continuar.'}</p><form onSubmit={handleSignIn} className="mt-8 flex flex-col gap-4"><input required type="email" placeholder="E-mail" value={email} onChange={e => setEmail(e.target.value)} className="w-full rounded-xl border border-ouro/25 bg-white/5 px-5 py-3 text-creme placeholder-bege outline-none transition focus:border-ouro focus:ring-2 focus:ring-ouro/20" /><input required minLength={8} type="password" placeholder="Senha (mínimo 8 caracteres)" value={password} onChange={e => setPassword(e.target.value)} className="w-full rounded-xl border border-ouro/25 bg-white/5 px-5 py-3 text-creme placeholder-bege outline-none transition focus:border-ouro focus:ring-2 focus:ring-ouro/20" />{error && <p role="alert" className="text-sm text-rubi">{error}</p>}<button disabled={loading} className="mt-2 w-full rounded-full bg-ouro px-5 py-3 font-label text-sm uppercase tracking-widest text-preto transition hover:bg-champanhe disabled:opacity-60">{loading ? 'Aguarde...' : register ? 'Criar conta' : 'Entrar'}</button></form><button type="button" onClick={() => { setRegister(!register); setError('') }} className="mt-6 text-sm text-bege underline underline-offset-4 transition hover:text-creme">{register ? 'Já tenho uma conta' : 'Ainda não tenho conta'}</button><p className="mt-8 text-sm"><Link to="/carrinho" className="text-ouro transition hover:text-champanhe">Voltar ao carrinho</Link></p></div></main>
}

export default SignIn1
